record:
  type: ApplicationDeploymentRequest
  version: 1.2.3
  application: application
  dns: dns
  config:
    env:
      ENV_VAR_A: A
      ENV_VAR_B: B
  crn:
    - crn://laconic-app.hypha.coop
  meta:
    foo: bar
  tags:
    - a
    - b